### ISSUE TITLE
Redundant comment handling code?

### ISSUE THREAD

**Issue by NetMage** [juwikuang/csv2entity#11]
In
`public static T[] ReadContext<T>(IEnumerable<string> records, CsvConfig config, Predicate<string> preFilter, Predicate<T> postFilter)`

Since you have
`list.RemoveAll(line => line.StartsWith("#"));`

Doesn't that mean that
`if (!list[i].StartsWith("#", StringComparison.OrdinalIgnoreCase))`

can never be false?

**Comment by juwikuang** [comment]
Hi NetMage, 

thanks for your feedback.

this function is in file CsvContext`1.cs, line 132.

Please be noticed that this function is marked as Obsolete. 

Well, the solution is simply delete it.

**Comment by juwikuang** [comment]
fixed

**Comment by juwikuang** [comment]
fixed
