### ISSUE TITLE
potential null reference for titles

### ISSUE THREAD

**Issue by NetMage** [juwikuang/csv2entity#12]
In this code:

    string[] titles = null;
    if (config.MappingType == CsvMappingType.Title) 
    { 
        titles = list[0].Split(new string[] { config.Delimiter }, StringSplitOptions.None); 
    } 

    for (int i = 0; i < titles.Length; i++) 

If `config.MappingType` is not `CsvMappingType.Title` then won't `titles.Length` be a null reference error?

**Comment by juwikuang** [comment]
thanks for your feedback , please be noticed that this function is decorated as [Obsolete("",true)], i will delete it in the future.

**Comment by ShuaiShuaiLee** [comment]
> 
> 
> thanks for your feedback , please be noticed that this function is decorated as [Obsolete("",true)], i will delete it.

你不是加入了996ICU License吗？那你这各个项目的licence 怎么没有更新呢！

**Comment by juwikuang** [comment]
fixed
